-- vim.opt.backspace = "2"
vim.opt.autoread = true
vim.opt.autowrite = true
vim.opt.cmdheight = 1
vim.opt.cursorline = true
vim.opt.expandtab = true
-- vim.opt.ignorecase = true
vim.opt.inccommand = "split"
-- vim.opt.showcmd = true
-- vim.opt.showmode = false
vim.opt.number = true
vim.opt.numberwidth = 1
vim.opt.relativenumber = true
vim.opt.scrolloff = 10
vim.opt.shiftwidth = 2
vim.opt.shiftround = true
-- vim.opt.smartcase = true
vim.opt.smartindent = true
vim.opt.signcolumn = "yes"
vim.opt.tabstop = 2
vim.opt.undofile = true
vim.opt.updatetime = 100
